return {
	terminal = "kitty",
	kbTerminal = "SUPER + Return",
	kbCommunicationWs = "SUPER + C",
	kbPinWindow = "SUPER + SHIFT + P",
	kbEditor = "SUPER + SHIFT + ALT + C",
	kbSystemMonitorWs = "SUPER + B", --editor = "nvim",
	--kbEditor = "SUPER + X",
	workspaceGaps = 20,
	windowGapsIn = 2,
	windowGapsOut = 10,
	singleWindowGapsOut = 20,
	kbWindowCycleNext = "",
	kbWindowGroupCycleNext = "ALT + TAB",
	windowBorderSize = 3,
}
