hl.window_rule({ match = { class = "^(kitty)$" }, no_blur = true })
hl.window_rule({ match = { class = "^(kitty)$" }, border_color = "rgba(1793d1DD) rgba(1793d177)" })
hl.window_rule({ match = { class = "^(Tk)$" }, float = true })
hl.window_rule({ match = { float = 1 }, center = true })
hl.window_rule({ match = { float = 1 }, size = { "(monitor_w*0.55)", "(monitor_h*0.6)" } })
